ICS Nerva - Library, Command Dorms swapped location + rework, Stowaway spawns added.
UristMcStation/UristMcStation pull request #1140
Opened 2023-06-23 21:43 UTC by Yantarii

### Proposed Changes:
- Stowaways now have additional spawn points around specific hidden areas of maintenance.
- Moving Library above the Bar.
- Moving Command Dorms to previous Library area (which suits being near dorms.)
- Adjusts Bar to accommodate for an additional stairway.

### Bar:

Bar has been slightly compacted further upwards one tile to accommodate a stairwell.
Adjusts some of the electronics, and lights around the bar to accommodate for this change.
Moves kitchen sink to the top of the Bar.

Images:

![1](https://github.com/UristMcStation/UristMcStation/assets/53942081/110a821d-641d-4969-9cf7-9562b31f363a)
![3](https://github.com/UristMcStation/UristMcStation/assets/53942081/abb69d0d-eee4-438d-a56f-2d1ac492940c)

### Library

Library has been moved to be above the Bar, allowing this area to be slightly more high-trafficked. This also should help facilitate additional roleplay oppertunities, i.e playing DnD with bar guests, etc. The Library has kept some of it's original damage as well, which can easily be repaired. There is a view down to the bottom level of the bar than can be used for all sorts of fun activities. The Library doesn't have direct line of sight to the teleporter area, meaning that traitors can still break into secure areas without too much difficulty, provided they take maintenance, or go to the north area of the library.

### Command Dorms:

Command Dorms have been moved near dorms itself, as it's seldom used.

![5](https://github.com/UristMcStation/UristMcStation/assets/53942081/40a85f11-9667-4baf-8851-586f87ad5f0c)

### As always with map changes, feedback is important, so please feel free to send feedback in #development channel, or here.

2023-06-23 22:05 UTC, CPU-Blanc requested changes
Only done a quick skim but there's some issues I've spotted.
Not sure why but it looks like your editor has added a bunch of whitespace into the beacon tags, which will break bot patrolling. Also a few sensors, which would break consoles properly linking to them

2023-06-23 22:05 UTC, CPU-Blanc commented on maps/nerva/nerva-3.dmm
> +	sensors = list("d2_c_chamber_sensor"="Combustion                                Chamber")
and again
```suggestion
	sensors = list("d2_c_chamber_sensor"="Combustion Chamber")
```

2023-06-23 22:05 UTC, CPU-Blanc commented on maps/nerva/nerva-3.dmm
> +	codes = list("patrol"=1,"next_patrol"="Deck                                2                                Aft                                Starboard");
as above
```suggestion
	codes = list("patrol"=1,"next_patrol"="Deck 2 Aft Starboard");
```

2023-06-23 22:05 UTC, CPU-Blanc commented on maps/nerva/nerva-3.dmm
> +	codes = list("patrol"=1,"next_patrol"="Deck                                2                                Fore                                Port");
another big boy
```suggestion
	codes = list("patrol"=1,"next_patrol"="Deck 2 Fore Port");
```

2023-06-23 22:05 UTC, CPU-Blanc commented on maps/nerva/nerva-3.dmm
> +	codes = list("patrol"=1,"next_patrol"="Deck                                1                                Port                                Docks");
long boy
```suggestion
	codes = list("patrol"=1,"next_patrol"="Deck 1 Port Docks");
```

2023-06-23 22:05 UTC, CPU-Blanc commented on maps/nerva/nerva-4.dmm
> +	codes = list("patrol"=1,"next_patrol"="Deck  1  Starboard  Docks");
as above
```suggestion
	codes = list("patrol"=1,"next_patrol"="Deck 1 Starboard Docks");
```

2023-06-23 22:05 UTC, CPU-Blanc commented on maps/nerva/nerva-4.dmm
> +	codes = list("patrol"=1,"next_patrol"="Deck  4  Escape");
again
```suggestion
	codes = list("patrol"=1,"next_patrol"="Deck 4 Escape");
```

2023-06-23 22:05 UTC, CPU-Blanc commented on maps/nerva/nerva-1.dmm
> +	sensors = list("d4_port_chamber_sensor"="Combustion  Chamber")
added whitespace
```suggestion
	sensors = list("d4_port_chamber_sensor"="Combustion Chamber")
```

2023-06-24 10:44 UTC, Yantarii commented
Weird, I'm using Visual Studio Code and StrongDMM. I'll fix them up in the next few days, thanks!

2023-08-09 04:24 UTC, Glloyd commented
I like the change, I've been wanting to add a second level to the bar for a while. it might be best to recreate this on the baymerge branch however, this will be quite difficult to merge into there from master.

2023-08-10 01:33 UTC, Yantarii commented
> I like the change, I've been wanting to add a second level to the bar for a while. it might be best to recreate this on the baymerge branch however, this will be quite difficult to merge into there from master.

Yeah I'm gonna close this and redo it for baymerge.

2023-08-10 01:33 UTC, closed without merging