[WIP] Ports Polaris's port of salvageable machines and computers
UristMcStation/UristMcStation pull request #1223
Opened 2023-09-26 03:19 UTC by CaraS212

Adds busted down machines and computers that can be crowbar'd apart for scrap.

I need feedback on what these things should give and how much. so far putting a burnt circuit board gives you maybe 7 or so steel. Other objects have lines saying they should be recycling into gold, silver, etc. while our lathes and i believe the trash crushers do not handle the recycling of advanced materials.

per the code for the trash items: list(MATERIAL_name, chance, amount)

2023-09-26 08:45 UTC, scrdest approved these changes

2023-09-26 08:45 UTC, scrdest commented on code/modules/urist/items/salvageable.dm
> +	var/salvageable_parts = list()
```suggestion
	var/list/salvageable_parts = list()
```
A bit clearer this way

2023-09-26 08:45 UTC, scrdest commented on code/modules/urist/items/salvageable.dm
> +	density = 1
```suggestion
	density = TRUE
```
Will pacify the linter

2023-09-26 09:15 UTC, CaraS212 commented
i cant tell if the code check is an indentation error this time, but i dont see anything immediate when  i highlight the added files

2023-09-26 11:02 UTC, scrdest commented on code/modules/urist/items/salvageable.dm
> +	anchored = 1
```suggestion
	anchored = TRUE
```
That's what it's failing at; the check wording is jank

2023-10-04 04:29 UTC, Glloyd commented on code/modules/urist/modules/newtrading/trade/trade_items/tools.dm
> -/datum/trade_item/tool/screwdriver
this shouldn't have been removed

2023-10-04 04:30 UTC, Glloyd requested changes
if you remove the trader stuff from this PR, we can get this merged. That should be for a future PR regardless of whether it works or not right now because there's balance considerations with prices; setting those trade prices will affect the prices the nerva gets for trading those items through cargo. Also, this will likely conflict with #1251 if you keep the NT station changes in here.

2023-10-04 05:50 UTC, CaraS212 commented
Ill strip out the trader stuff tomorrow and open a new draft.

2023-10-05 00:50 UTC, CaraS212 commented
removed station file entirely as it has been replaced by a 2 part dmm file

2023-10-05 04:15 UTC, Glloyd commented on code/modules/urist/items/salvageable.dm
> +	name = "broken macninery"
```suggestion
	name = "broken machinery"
```

2023-10-05 04:15 UTC, Glloyd commented on code/modules/urist/items/salvageable.dm
> +	desc = "Despite being in pristine condition this console doesn't respond to anything, but looks like you can still salvage something from this."
```suggestion
	desc = "Despite being in pristine condition this console doesn't respond to anything, but it looks like you can still salvage something from this."
```

2023-10-05 04:17 UTC, Glloyd approved these changes
this'll be great for awaymaps 👍

2023-10-05 04:36 UTC, merged