Setup Nerva-Specific Lobby Music List.
UristMcStation/UristMcStation pull request #1416
Opened 2024-03-18 23:42 UTC by Yantarii

Bay added functionality for this a while back
Now you don't have Swedish House Mafia blowing your eardrums out.

It'll only play whatever tracks are in this list, yippee!!

2024-03-18 23:50 UTC, CPU-Blanc approved these changes

2024-03-19 08:39 UTC, scrdest requested changes

2024-03-19 08:39 UTC, scrdest commented on maps/nerva/nerva_define.dm
> +		/singleton/audio/track/rimward_cruise,
```suggestion
		/singleton/audio/track/human,
		/singleton/audio/track/level3_mod,
		/singleton/audio/track/lysendraa,
		/singleton/audio/track/rimward_cruise,
```
Just realized this morning there's another classic missing (level3_mod is the goofy jazzy track). I can live without dilbert, but level3_mod is a hill I will happily die on.

2024-04-02 13:39 UTC, Yantarii commented
Updated.

2024-04-02 20:42 UTC, scrdest approved these changes
many t.hanks!

![images](https://github.com/UristMcStation/UristMcStation/assets/4363639/6a569a94-29db-4258-9f8f-4a05fa587a8a)

2024-04-02 20:45 UTC, merged