Adds additional movie titles to Bay's End of Round Credits.
UristMcStation/UristMcStation pull request #1431
Opened 2024-04-06 15:30 UTC by Yantarii

Adds a whole bunch of additional movie titles to the round end, even if we baymerge again, it shouldn't be too hard to just copy our new one.

Removed references to GAS and Serpentids, and added IPCs and Resomi.

2024-04-06 17:00 UTC, CPU-Blanc commented on code/game/movietitles.dm
> +		possible_titles += "A VERY [pick("CORPORATE", "NANOTRASEN", "FLEET", "TERRAN", "LACTERAN", "HAPHAESTUS", "DAIS", "XENOLIFE", "EXPEDITIONARY", "DIONAN", "PHORON", "MARTIAN", "RESOMI")] [pick("CHRIST
Could be fun to use the actual day here instead :P
```suggestion
		possible_titles += "A VERY [pick("CORPORATE", "NANOTRASEN", "FLEET", "TERRAN", "LACTERAN", "HAPHAESTUS", "DAIS", "XENOLIFE", "EXPEDITIONARY", "DIONAN", "PHORON", "MARTIAN", "RESOMI")] [pick("CHRISTMAS", "EASTER", "HOLIDAY", "VACATION", uppertext(time2text(world.realtime, "Day")), "NEW YEARS", "BOXING DAY")]"
```

2024-04-06 17:11 UTC, CPU-Blanc requested changes
Some spelling and grammar issues

2024-04-06 17:11 UTC, CPU-Blanc commented on code/game/movietitles.dm
> +							"THE SUPERMATTER CRYSTAL", "MEDICAL", "ENGINEERING", "SECURITY", "RESEARCH", "THAT ONE LAST CREWMATE", "THE SERVICE DEPARTMENT", "COMMAND", "THE EXPLORERS", "THE AWAY TEAM", "THE BOTANIST", "T
```suggestion
							"THE SUPERMATTER CRYSTAL", "MEDICAL", "ENGINEERING", "SECURITY", "RESEARCH", "THAT ONE LAST CREWMATE", "THE SERVICE DEPARTMENT", "COMMAND", "THE EXPLORERS", "THE AWAY TEAM", "THE BOTANIST", "THE CHEF", "BREATHABLE AIR", "THE KITCHEN", "THE BAR", "THE BARTENDER", "THE [uppertext(GLOB.using_map.station_name)]")]"
```

2024-04-06 17:11 UTC, CPU-Blanc commented on code/game/movietitles.dm
> +		possible_titles += "THE CREW [pick("FALL OUT A AIRLOCK", "LOOKS UP", "FUCKING DIES", "DESTROY THE [uppertext(GLOB.using_map.station_short)]", "DON'T DO ANYTHING", "GOES TO HELL", "GOES TO SPACE PRI
```suggestion
		possible_titles += "THE CREW [pick("FALL OUT AN AIRLOCK", "LOOKS UP", "FUCKING DIES", "DESTROY THE [uppertext(GLOB.using_map.station_short)]", "DON'T DO ANYTHING", "GOES TO HELL", "GOES TO SPACE PRISON", "EATS PACKING PEANUTS", "FORGET HOW TO BE KIND",  "MOVE TO AN EXOPLANET", "CATCH A STOWAWAY", "FALL OUT A WINDOW", "SETTLE A LAWSUIT", "BUY A NEW SHIP", "FIND A DEAD GUY", "LOVES [pick("MEDBAY", "ALCOHOL", "YOU", "UNREGISTERED GUNS", "MONKEY CUBES", "MAKING A MESS", "ANNOYING COMMAND", "GETTING BRIGGED")]")]"
```

2024-04-06 17:11 UTC, CPU-Blanc commented on code/game/movietitles.dm
> +							"[pick("UNATHI", "SKRELLIAN", "DIONAN", "RESOMI", "VOX", "IPC")] MATING RITUALS", "ANCIENT CHINESE MEDICINE", "THE IMPORTANCE OF [pick("AIRLOCK SAFETY", "MAINTENANCE", "SUIT SENSORS", "FLOOR P
```suggestion
							"[pick("UNATHI", "SKRELLIAN", "DIONAN", "RESOMI", "VOX", "IPC")] MATING RITUALS", "ANCIENT CHINESE MEDICINE", "THE IMPORTANCE OF [pick("AIRLOCK SAFETY", "MAINTENANCE", "SUIT SENSORS", "FLOOR PILLS", "ELEVATORS", "HEIGHTS", "TORPEDOES", "GOOD RELATIONS", "A FULLY STOCKED BAR", "AWAY MISSIONS", "MANDATORY DRUG TESTING", "HIRING SECURITY", "GOOD FORENSICS", "TEST WIRES", "UNIONS", "NEURAL LACES", "ENGINEERS")]")]"
```

2024-04-06 17:11 UTC, CPU-Blanc commented on code/game/movietitles.dm
> +		possible_titles += "[pick("GUNS, GUNS EVERYWHERE", "THE LITTLEST ARMALIS", "WHAT HAPPENS WHEN YOU MIX MAINTENANCE DRONES AND COMMERCIAL-GRADE PACKING FOAM", "INTERNALLY COHERANT, HARDCORE CRAZY TO
```suggestion
		possible_titles += "[pick("GUNS, GUNS EVERYWHERE", "THE LITTLEST ARMALIS", "WHAT HAPPENS WHEN YOU MIX MAINTENANCE DRONES AND COMMERCIAL-GRADE PACKING FOAM", "INTERNALLY COHERENT, HARDCORE CRAZY TO THE MEGA", "ATTACK! ATTACK! ATTACK!", "SEX BOMB", "THE LEGEND OF THE ALIEN ARTIFACT: PART [pick("I","II","III","IV","V","VI","VII","VIII","IX", "X", "C","M","L")]")]"
```

2024-04-06 17:11 UTC, CPU-Blanc commented on code/game/movietitles.dm
>  		possible_titles += "[pick("SPACE", "SEXY", "DRAGON", "WARLOCK", "LAUNDRY", "GUN", "ADVERTISING", "DOG", "CARBON MONOXIDE", "NINJA", "WIZARD", "SOCRATIC", "JUVENILE DELIQUENCY", "POLITICALLY MOTIVAT
I know this wasn't you, but.. mistake here lmao
```suggestion
		possible_titles += "[pick("SPACE", "SEXY", "DRAGON", "WARLOCK", "LAUNDRY", "GUN", "ADVERTISING", "DOG", "CARBON MONOXIDE", "NINJA", "WIZARD", "SOCRATIC", "JUVENILE DELINQUENCY", "POLITICALLY MOTIVATED", "RADTACULAR SICKNASTY")] [pick("QUEST", "FORCE", "ADVENTURE")]"
```

2024-04-08 14:54 UTC, Yantarii commented
Should be most of it fixed!

2024-04-08 16:22 UTC, CPU-Blanc approved these changes
LGTM

2024-04-12 00:15 UTC, merged