Adds additional Holomaps & a wheelchair to Nerva
UristMcStation/UristMcStation pull request #1434
Opened 2024-04-06 18:01 UTC by Yantarii

This adds additional Holomaps all around the Nerva, usually near key and memorable areas, or specific hallways.
The intent is to make it easier for new players to look around the map aside from viewing that one pinned PNG

**Locations:**

**Deck 1:**
Bottom of Trajan Hangar

**Deck 2:**
Cryo Storage
Bar
Near Security Lobby
Holodeck

**Deck 3:**

Near Deck 3 Stairway Elevator.
Dormitory
Observatory
Near Teleporter Outside.

**Deck 4:**
Top Docking Port.

This also adds a singular wheelchair in the Medical Storage Bay.

**TODO:**

- [ ] Check all dir are working correctly.

2024-04-06 18:34 UTC, CPU-Blanc requested changes
This branch is out of date and regresses previous map changes, notably ones made in #1418 . You'll need to rebase onto baymerge-testing

2024-04-08 16:44 UTC, CPU-Blanc requested changes

2024-04-08 16:44 UTC, CPU-Blanc commented on maps/nerva/nerva-1.dmm
The map in the hanger is the wrong direction and in the middle of the floor

2024-04-08 16:48 UTC, CPU-Blanc reviewed
Like the idea, however, I have a couple of issues/points.

- Some of the maps' overlays appear to spawn on the wrong tile, and kinda just float in mid-air. This looks odd and would ideally be fixed
- The placement sometimes feels a little random? ie the one outside the teleporter and inside cargo. Is there a way to make them a little more uniform? ie outside stairs, evenly spaced in public hallways in the same tough position on each floor?

2024-04-08 16:48 UTC, CPU-Blanc commented on maps/nerva/nerva-3.dmm
- Holomap outside the elevator is literally like 5 steps from another one, do we need them this close?
- Holomap in the dorms overlaps the camera and looks odd
- Holomap in the starboard observatory overlaps a light and looks odd

2024-04-08 17:09 UTC, Yantarii commented on maps/nerva/nerva-3.dmm
I'll do a pass tonight and make some changes, need to fix the weird dir issues as well

2024-04-12 00:22 UTC, Glloyd commented on maps/nerva/nerva-3.dmm
yeah, they definitely don't need to be that close, especially because they do have a slight performance impact while in use iirc

2024-05-19 01:07 UTC, closed without merging