Additional Example Map Additions:
UristMcStation/UristMcStation pull request #1522
Opened 2024-07-21 10:12 UTC by Yantarii

![image](https://github.com/user-attachments/assets/754c3c44-7d06-442d-a87c-cbdaa795d352)

Suit Cycler, Suit Storage, Premade Mech, Captain's Spare.

![image](https://github.com/user-attachments/assets/d8f494dc-2399-45c9-ae34-d8687242bd47)
A whole bunch of missing machinery - mainly botanical, kitchen, lathes, etc.
Atmos adjustments.
Additional material stacks including sheets of animal produce, etc.

![image](https://github.com/user-attachments/assets/03396594-fd42-4565-bb0f-f943ef0fcf39)

All vendors in SS13, and the tools to hack and modify them.
Since most items are gotten through vendors, it's nice to have them all in one place.

2024-07-27 23:37 UTC, CPU-Blanc requested changes

2024-07-27 23:37 UTC, CPU-Blanc commented on maps/example/example-3.dmm
Honestly not a fan of this. A large empty space is great for testing, and these vending machines feel very situational, rather than something that should always be there. They could simply be spawned in as and when required.

2024-07-29 23:26 UTC, Yantarii commented on maps/example/example-3.dmm
Removed all of the vendors in example-3 and everything else changed

2024-07-29 23:34 UTC, CPU-Blanc approved these changes

2024-07-30 06:28 UTC, merged